# Tugas Besar Machine Learning Eksperimen

## confused matrix, akurasi, presisi, recall, F1

In [109]:
import math
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm,datasets,model_selection,metrics,neural_network

In [110]:
def confused_matrix(y_true,y_pred):
    tp = 0
    fp = 0
    fn = 0
    tn = 0
    for i in range (len(y_pred)):
        if(y_pred[i] == 1 and y_true[i] == 1):tp = tp + 1 # true positive
        elif(y_pred[i] == 1 and y_true[i] == 0):fp = fp + 1 # false positive
        elif(y_pred[i] == 0 and y_true[i] == 1):fn = fn + 1 # false negative
        elif(y_pred[i] == 0 and y_true[i] == 0):tn = tn + 1 # true negative
    return tp,fp,fn,tn

def accuracy(tp,fp,fn,tn):
    return((tp+tn)/(tp+fp+fn+tn))

def precision(tp,fp): #PPV
    return(tp/(tp+fp))

def recall(tp,fn): #TPR (bukan dibaca tepar)
    return(tp/(tp+fn))

def f1(tp,fp,fn):
    return((2*tp)/(2*tp+fp+fn))


In [111]:
y_pred = [0,0,1,0,1,0,1,0,0,1]
y_true = [0,1,1,1,0,1,0,0,1,0]
tp,fp,fn,tn = confused_matrix(y_true,y_pred)
print("hasil implementasi")
print("tp ",str(tp))
print("fp ",str(fp))
print("fn ",str(fn))
print("tn ",str(tn))
print("accuracy ",str(accuracy(tp,fp,fn,tn)))
print("precision ",str(precision(tp,fp)))
print("recall ",str(recall(tp,fn)))
print("f1 ",str(f1(tp,fp,fn)))
print("hasil SKlearn")
tn1, fp1, fn1, tp1 = metrics.confusion_matrix(y_true,y_pred).ravel()
print("tp ",str(tp1))
print("fp ",str(fp1))
print("fn ",str(fn1))
print("tn ",str(tn1))
print("accuracy ",str(metrics.accuracy_score(y_true,y_pred)))
print("precision ",str(metrics.precision_score(y_true,y_pred)))
print("recall ",str(metrics.recall_score(y_true,y_pred)))
print("f1 ",str(metrics.f1_score(y_true,y_pred)))

hasil implementasi
tp  1
fp  3
fn  4
tn  2
accuracy  0.3
precision  0.25
recall  0.2
f1  0.2222222222222222
hasil SKlearn
tp  1
fp  3
fn  4
tn  2
accuracy  0.3
precision  0.25
recall  0.2
f1  0.22222222222222224


## FFNN Learning dataset iris

In [119]:
X, y = datasets.load_iris(return_X_y=True)
class_names = datasets.load_iris().target_names
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.1,train_size=0.9)
classifier = svm.SVC(kernel='linear', C=0.01).fit(X_train, y_train)
np.set_printoptions(precision=2)
titles_options = [("Confusion matrix", None)]
for title, normalize in titles_options:
    disp = metrics.plot_confusion_matrix(classifier, X_test, y_test,
                                 display_labels=class_names,
                                 cmap=plt.cm.Blues,
                                 normalize=normalize)
    disp.ax_.set_title(title)

    print(title)
    print(disp.confusion_matrix)
plt.show()

Confusion matrix
[[4 0 0]
 [0 5 1]
 [0 0 5]]


ValueError: Found input variables with inconsistent numbers of samples: [15, 135]